### ISSUE TITLE
About the h4, h5, h6 in blockquotes

### ISSUE THREAD

**Issue by Toyimo** [HereIsLz/Fluent-Typora#1]
Hi, the interesting guy who designed Fluent theme, I'm sorry to bother you,  when I try to use h4, h5 and h6 in blockquotes, I found that there is no related symbol such as the example picture,  it shows like □
很抱歉打扰到您，不介意的话后面我就用中文了哈
我注意到那块儿代码用到的是"思源宋体 CN"字符代码\f097所对应的符号
但我下载到的“思源宋体 CN”好像并没有这个字符
能不能麻烦您提供一下您的字体链接啊T^T
Thank you very much

**Comment by li3zhen1** [comment]
你好，非常抱歉忘记将字体文件加入。问题已经修复，请更新 fluent.css 并把仓库中的 fluent 文件夹放到 Typora 主题文件夹中的对应位置 (./fluent)。
