### ISSUE TITLE
Bookmark Icon

### ISSUE THREAD

**Issue by nickwild-999** [HereIsLz/Fluent-Typora#14]
How do you use the Bookmark and other icons with this theme?

**Comment by li3zhen1** [comment]
To use the icons, see https://github.com/HereIsLz/Fluent-Typora#escapings .
To add your own icons, convert any SVG file to base64 format and replace them in the CSS files.
All the icons used in this theme are from https://github.com/microsoft/fluentui-system-icons .

**Comment by nickwild-999** [comment]
Thanks @HereIsLz I got the Bookmark working but not the other icons. Can you give me some examples of the syntax for their use outside the # for bookmark. Thanks

**Comment by li3zhen1** [comment]
Sorry I didn't make it clear. Just change single `#` to `##` / `###` ... and you will get other icons. And these icons are rendered only if the headline is placed at the first line of a blockquote.

**Comment by li3zhen1** [comment]
```
> ### Another Icon
> This is `H3` inside a block quote.
```
