### ISSUE TITLE
Some logical operators in code are getting replaced

### ISSUE THREAD

**Issue by henshin** [HereIsLz/Fluent-Typora#17]
I've noticed that some logical operators such as `!=` or `!==` are being replaced by a single character in the code blocks.
Example:
![image](https://user-images.githubusercontent.com/7304307/149346875-7797e68e-dd89-4cd6-a8b1-22818d82b811.png)

I don't see these replacements if I switch to another theme.
Can you disable this?

**Comment by li3zhen1** [comment]
Hi,
search for `font-variant-ligatures` and replace the corresponding line like this:

**FROM**
```css
    font-variant-ligatures: common-ligatures!important;
    font-feature-settings: "liga" 1!important;
```

**TO**
```css
    font-variant-ligatures: none!important;
    font-feature-settings: "liga" 0!important;
```

For more detailed control, check out  https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures .
