### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by simprecicchiani** [HereIsLz/Fluent-Typora#2]
Hey, thanks for the beautiful work. Have you thought of making a dark version of the theme? I think it would look awesome!

PS: not completely dark like #000000 but in line with the colour scheme of Fluent design

**Comment by li3zhen1** [comment]
See fluent-dark.css. It's not exactly the same with the original one. I'll keep on updating.

**Comment by simprecicchiani** [comment]
I'm sorry I didn't see it. I went straight on the release page. Thank you.
