### ISSUE TITLE
Dark version

### ISSUE THREAD

**Issue by adamhalesworth** [HereIsLz/Fluent-Typora#4]
I love using this theme during the day, but have to switch to something else at night for easier reading. Do you have any plans for a dark version? Happy to work on it if you don't have the time 👍

**Comment by li3zhen1** [comment]
Hi. Currently you can use [fluent-dark.css](https://github.com/HereIsLz/Fluent-Typora/blob/main/fluent-dark.css). This is not 
a completed version. I'll work on that later.

**Comment by adamhalesworth** [comment]
Thanks for the response @HereIsLz. I'll check it out.

**Comment by li3zhen1** [comment]
Hi,

A new version with built-in dark mode has been released. Try it out and any feedback is welcomed. Thanks.

**Comment by adamhalesworth** [comment]
Excellent, the contrast and colours are on point, very nice.
