### ISSUE TITLE
Request for a dark version of Fluent

### ISSUE THREAD

**Issue by j-peeters** [HereIsLz/Fluent-Typora#5]
Hi, 

Thanks for your beautiful theme. I was wondering if you would be willing to create a dark mode version for this theme?

Thanks, Jan

**Comment by li3zhen1** [comment]
Hi,

For now I recommend you using `fluent-dark.css` in the root directory of this repo. Later i'll release a better version. Thanks.

**Comment by j-peeters** [comment]
Terrific thanks.

**Comment by li3zhen1** [comment]
Hi,

A new version with built-in dark mode has been released. Try it out and any feedback is welcomed. Thanks.

**Comment by j-peeters** [comment]
Hi @HereIsLz, it looks terrific. Thanks!
