### ISSUE TITLE
深色模式导出PDF正文背景是浅色

### ISSUE THREAD

**Issue by 85Ryan** [HereIsLz/Fluent-Typora#7]
深色模式下，导出PDF正文背景是浅色。
如图：
<img width="881" alt="ScreenShot 1" src="https://user-images.githubusercontent.com/3353632/118509308-7efb2b80-b762-11eb-963b-316ea1569a25.png">

**Comment by li3zhen1** [comment]
你好，
通常深色模式仅被用于屏幕显示，在打印时输出的 pdf 为亮色模式是预期的行为。
如果希望输出深色模式的 pdf，请换用 `fluent-dark.css`。
